backup_jokes = [
  "Did you hear about the new restaurant on the moon? The food is great, but there\u2019s just no atmosphere.",
  "What do you do when your bunny gets wet? You get your hare dryer.",
  "My boss told me that he was going to fire the person with the worst posture. I have a hunch, it might be me.",
  "What's the best thing about elevator jokes? They work on so many levels.",
  "My sea sickness comes in waves.",
  "What did the fish say when it swam into a wall? Damn!",
  "I was going to get a brain transplant, but I changed my mind",
  "Do I enjoy making courthouse puns? Guilty",
  "Chances are if you' ve seen one shopping center, you've seen a mall.",
  "What do you get when you cross a bee and a sheep? A bah-humbug.\r\n",
  "They're making a movie about clocks. It's about time",
  "At the boxing match, the dad got into the popcorn line and the line for hot dogs, but he wanted to stay out of the punchline.",
  "You can't run through a camp site. You can only ran, because it's past tents.",
  "Today a man knocked on my door and asked for a small donation towards the local swimming pool. I gave him a glass of water.",
  "What is a vampire's favorite fruit? A blood orange.",
  "To the person who stole my anti-depressant pills: I hope you're happy now.",
  "I burned 2000 calories today, I left my food in the oven for too long.",
  "What do you call an alligator in a vest? An in-vest-igator!",
  "A red and a blue ship have just collided in the Caribbean. Apparently the survivors are marooned.",
  "Where do young cows eat lunch? In the calf-ateria.",
  "What\u2019s the advantage of living in Switzerland? Well, the flag is a big plus.",
  "Why did the feline fail the lie detector test? Because he be lion.",
  "How was the snow globe feeling after the storm? A little shaken.",
  "If a child refuses to sleep during nap time, are they guilty of resisting a rest?",
  "Conjunctivitis.com \u2013 now that\u2019s a site for sore eyes.",
  "What did Romans use to cut pizza before the rolling cutter was invented? Lil Caesars",
  "What did celery say when he broke up with his girlfriend? She wasn't right for me, so I really don't carrot all.",
  "So, I heard this pun about cows, but it\u2019s kinda offensive so I won\u2019t say it. I don\u2019t want there to be any beef between us. ",
  "What type of music do balloons hate? Pop music!",
  "Why did the octopus beat the shark in a fight? Because it was well armed.",
  "What do you call a beehive without the b's? An eehive.",
  "How did Darth Vader know what Luke was getting for Christmas? He felt his presents.",
  "Why can't a bicycle stand on its own? It's two-tired.",
  "Parallel lines have so much in common. It\u2019s a shame they\u2019ll never meet.",
  "What did the father tomato say to the baby tomato whilst on a family walk? Ketchup.",
  "What do you call a fat psychic? A four-chin teller.",
  "What do bees do after they are married? They go on a honeymoon.",
  "Why do cows wear bells? Because their horns don't work.",
  "How do you make Lady Gaga cry? Poker face. ",
  "Why can\u2019t you hear a pterodactyl go to the bathroom? The p is silent.",
  "I have kleptomania, but when it gets bad, I take something for it.",
  "Whiteboards ... are remarkable.",
  "Why do fish live in salt water? Because pepper makes them sneeze!",
  "Why do scuba divers fall backwards into the water? Because if they fell forwards they\u2019d still be in the boat.",
  "Two peanuts were walking down the street. One was a salted",
  "I used to work for a soft drink can crusher. It was soda pressing.",
  "Ever wondered why bees hum? It's because they don't know the words.",
  "What did the grape do when he got stepped on? He let out a little wine.",
  "Recent survey revealed 6 out of 7 dwarf's aren't happy.",
  "How much does a hipster weigh? An instagram.",
  "Chances are if you' ve seen one shopping center, you've seen a mall.",
  "How come a man driving a train got struck by lightning? He was a good conductor.",
  "Don\u2019t interrupt someone working intently on a puzzle. Chances are, you\u2019ll hear some crosswords.",
  "Why can\u2019t you hear a pterodactyl go to the bathroom? The p is silent.",
  "It's only a murder of crows if there's probable caws.",
  "If a child refuses to sleep during nap time, are they guilty of resisting a rest?",
  "What do you call a cow with two legs? Lean beef.",
  "How come the stadium got hot after the game? Because all of the fans left.",
  "Egyptians claimed to invent the guitar, but they were such lyres.\ufeff",
  "Have you heard about corduroy pillows?  They're making headlines!",
  "What kind of tree fits in your hand? A palm tree!",
  "My wife is on a tropical fruit diet, the house is full of stuff. It is enough to make a mango crazy.",
  "The Swiss must've been pretty confident in their chances of victory if they included a corkscrew in their army knife.",
  "A red and a blue ship have just collided in the Caribbean. Apparently the survivors are marooned.",
  "What do you call a magician who has lost their magic? Ian.",
  "What do you call an elephant that doesn\u2019t matter? An irrelephant.",
  "Ben & Jerry's really need to improve their operation. The only way to get there is down a rocky road.",
  "Q: What did the spaghetti say to the other spaghetti?\r\nA: Pasta la vista, baby!",
  "What kind of magic do cows believe in? MOODOO.",
  "Some people eat light bulbs. They say it's a nice light snack.",
  "Where do young cows eat lunch? In the calf-ateria.",
  "Wife told me to take the spider out instead of killing it... We had some drinks, cool guy, wants to be a web developer.",
  "What do you get when you cross a snowman with a vampire? Frostbite.",
  "Guy told me today he did not know what cloning is. I told him, \"that makes 2 of us.\"",
  "Mahatma Gandhi, as you know, walked barefoot most of the time, which produced an impressive set of calluses on his feet. \r\nHe also ate very little, which made him rather frail and with his odd diet, he suffered from bad breath. \r\nThis made him a super calloused fragile mystic hexed by halitosis.",
  "Why don\u2019t skeletons ever go trick or treating? Because they have nobody to go with.",
  "Did you know the first French fries weren't actually cooked in France? They were cooked in Greece.",
  "You know that cemetery up the road? People are dying to get in there.",
  "They tried to make a diamond shaped like a duck. It quacked under the pressure.",
  "My dog used to chase people on a bike a lot. It got so bad I had to take his bike away.",
  "Wife: Honey I\u2019m pregnant.\r\n\r\nMe: Well\u2026. what do we do now?\r\n\r\nWife: Well, I guess we should go to a baby doctor.\r\n\r\nMe: Hm.. I think I\u2019d be a lot more comfortable going to an adult doctor.",
  "What happens to a frog's car when it breaks down? It gets toad.",
  "What do you call a bee that lives in America? A USB.",
  "What do you call a fly without wings? A walk.",
  "I tried to write a chemistry joke, but could never get a reaction.",
  "R.I.P. boiled water. You will be mist.",
  "What did the mountain climber name his son? Cliff.",
  "What did the late tomato say to the early tomato? I\u2019ll ketch up",
  "A cannibal is someone who is fed up with people.",
  "What did the grape do when he got stepped on? He let out a little wine.",
  "What do you call your friend who stands in a hole? Phil.",
  "A Skeleton walked into a bar he said I need a beer and a mop",
  "I bought shoes from a drug dealer once. I don't know what he laced them with, but I was tripping all day.",
  "At the boxing match, the dad got into the popcorn line and the line for hot dogs, but he wanted to stay out of the punchline.",
  "Why are graveyards so noisy? Because of all the coffin.",
  " I never wanted to believe that my Dad was stealing from his job as a road worker. But when I got home, all the signs were there.\r\n\r\n",
  "This morning I was wondering where the sun was, but then it dawned on me.",
  "What do you call an Argentinian with a rubber toe? Roberto",
  "What did the Zen Buddist say to the hotdog vendor? Make me one with everything.",
  "What do you get when you cross a chicken with a skunk? A fowl smell!"
]