backup_quotes = [
  "Courage is what it takes to stand up and speak. Courage is also what it takes to sit down and listen. - Winston Churchill",
  "Dreams are the royal road to the unconscious.  - Sigmund Freud",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "Understanding that rests in what it does not understand is the finest. - Zhuangzi",
  "You are the average of the five people you spend the most time with. - Jim Rohn",
  "Never stand begging for that which you have the power to earn. - Miguel de Cervantes",
  "There is no fear for one whose mind is not filled with desires. - Buddha",
  "The more you are motivated by Love, The more Fearless & Free your action will be. - Dalai Lama",
  "The season of failure is the best time for sowing the seeds of success.  - Paramahansa Yogananda",
  "Every man is guilty of all the good he did not do.  - Voltaire",
  "What is planted in each person's soul will sprout.   - Rumi",
  "Be curious, not judgmental. - Walt Whitman",
  "Knowing others is wisdom, knowing yourself is enlightenment. - Lao Tzu",
  "Life begins where fear ends. - Osho",
  "A very little key will open a very heavy door. - Charles Dickens",
  "Never give up work. Work gives you meaning and purpose and life is empty without it. - Stephen Hawking",
  "Don't give up on your dreams, or your dreams will give up on you. - John Wooden",
  "Blessed is he who expects nothing, for he shall never be disappointed. - Alexander Pope",
  "Wheels of justice grind slow but grind fine. - Sun Tzu",
  "Believe in your infinite potential. Your only limitations are those you set upon yourself. - Roy T. Bennett",
  "Most people spend more time and energy going around problems than in trying to solve them.  - Henry Ford",
  "Let the beauty of what you love be what you do. - Rumi",
  "Death and life have their determined appointments; riches and honors depend upon heaven.  - Confucius ",
  "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine. - Roy T. Bennett",
  "Be as simple as you can be; you will be astonished to see how uncomplicated and happy your life can become. - Paramahansa Yogananda",
  "An inventor is a man who asks Why? of the universe and lets nothing stand between the answer and his mind. - Ayn Rand",
  "Any fool can turn a blind eye but who knows what the ostrich sees in the sand. - Samuel Beckett",
  "It is indeed a radical act of love just to sit down and be quiet for a time by yourself. - Jon Kabat-Zinn",
  "Faults are yours to fix, not to curse. - Colin Powell",
  "Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.  - Laozi",
  "Unless a man is master of his soul, all other kinds of mastery amount to little. - Theodore Roosevelt",
  "Instead of worrying about what you cannot control, shift your energy to what you can create. - Roy T. Bennett",
  "A fool sees himself as another, but a wise man sees others as himself. - Dogen",
  "The beautiful journey of today can only begin when we learn to let go of yesterday. - Steve Maraboli",
  "The greatest value of a picture is when it forces us to notice what we never expected to see. - John Tukey",
  "A man who dares to waste one hour of time has not discovered the value of life. - Charles Darwin",
  "Before anything else, preparation is the key to success. - Alexander Graham Bell",
  "Monsters are real, and ghosts are real too. They live inside us, and sometimes, they win. - Stephen King",
  "Empty yourself of everything - let the mind become still. - Lao Tzu",
  "Catch, then, O catch the transient hour; Improve each moment as it flies!  - St. Jerome",
  "Take interest and even delight in doing the small things well. - Jim Rohn",
  "When you are tough on yourself, life is going to be infinitely easier on you.   - Zig Ziglar",
  "At every moment where language can't go, that's your mind. - Bodhidharma",
  "The decisions of our past are the architects of our present. - Dan Brown",
  "Why fit in when you were born to stand out? - Dr. Seuss",
  "It is often safer to be in chains than to be free.  - Franz Kafka",
  "The one who boasts does so only out of a feeling of inferiority. - Alfred Adler",
  "You were put on this earth to achieve your greatest self, to live out your purpose, and to do it courageously. - Steve Maraboli",
  "Whenever you find yourself on the side of the majority, it is time to reform. - Mark Twain",
  "We love the things we love for what they are. - Robert Frost",
  "The journey, not the destination matters. - T.S. Eliot",
  "Good entrepreneurs don't fail because they stay at it. - Naval Ravikant",
  "In youth we run into difficulties. In old age difficulties run into us.  - Beverly Sills",
  "Every traveler has a home of his own, and he learns to appreciate it the more from his wandering. - Charles Dickens",
  "Every day is lost in which we do not learn something useful. Man has no nobler or more valuable possession than time. - Thomas Jefferson",
  "Goodness is the only investment that never fails. - Henry David Thoreau",
  "Be the reason someone smiles. Be the reason someone feels loved and believes in the goodness in people. - Roy T. Bennett",
  "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
  "An intelligence test sometimes shows a man how smart he would have been not to have taken it. - Laurence J. Peter",
  "Happiness is when what you think, what you say, and what you do are in harmony. - Mahatma Gandhi",
  "A scientific man ought to have no wishes, no affections, - a mere heart of stone. - Charles Darwin",
  "In matters of style, swim with the current; in matters of principle, stand like a rock. - Thomas Jefferson",
  "If we have no peace, it is because we have forgotten that we belong to each other. - Mother Teresa",
  "He who possesses most must be most afraid of loss. - Leonardo da Vinci",
  "If he cannot stop the mind that seeks after fame and profit, he will spend his life without finding peace. - Dogen",
  "Whenever you find yourself on the side of the majority, it is time to reform. - Mark Twain",
  "My mind seems to have become a kind of machine for grinding general laws out of large collections of facts. - Charles Darwin",
  "If you take responsibility for yourself you will develop a hunger to accomplish your dream. - Les Brown",
  "At every moment where language can't go, that's your mind. - Bodhidharma",
  "We take care of the future best by taking care of the present now. - Jon Kabat-Zinn",
  "Where there is no struggle, there is no strength.  - Oprah Winfrey",
  "Blessed is he who expects nothing, for he shall never be disappointed. - Alexander Pope",
  "My favorite things in life don't cost any money. It's really clear that the most precious resource we all have is time. - Steve Jobs",
  "Dreams are the touchstones of our characters. - Henry David Thoreau",
  "The meaning of life is that it stops. - Franz Kafka",
  "The longer we dwell on our misfortunes, the greater is their power to harm us. - Voltaire",
  "The harder the conflict, the greater the triumph.  - George Washington",
  "Unless you're ashamed of yourself now and then, you're not honest. - William Faulkner",
  "Character is the result of two things: mental attitude and the way we spend our time. - Elbert Hubbard",
  "The power of human thought grows exponentially with the number of minds that share that thought. - Dan Brown",
  "Our life isn't how much we can take out, but how much we can put in.   - Estee Lauder",
  "While we may not be able to control all that happens to us, we can control what happens inside us. - Benjamin Franklin ",
  "Be where your enemy is not. - Sun Tzu",
  "Don't let the noise of others' opinions drown out your own inner voice. - Steve Jobs",
  "We would accomplish many more things if we did not think of them as impossible. - Vince Lombardi",
  "Avoiding failure is to avoid progress. - Unknown",
  "It is important to fight and fight again, and keep fighting, for only then can evil be kept at bay though never quite eradicated. - Albus Dumbledore",
  "Love the life you live, live the life you love. - Bob Marley",
  "When you want to be honored by others, you learn to honor them first. - Sathya Sai Baba",
  "Go confidently in the direction of your dreams! Live the life you've imagined. - Henry David Thoreau",
  "If you correct your mind, the rest of your life will fall into place. - Lao Tzu",
  "It is indeed a radical act of love just to sit down and be quiet for a time by yourself. - Jon Kabat-Zinn",
  "Even the smallest person can change the course of the future. - J.R.R. Tolkien",
  "To live is the rarest thing in the world. Most people exist, that is all.  - Oscar Wilde",
  "Remember that sometimes not getting what you want is a wonderful stroke of luck. - Dalai Lama",
  "Consider the rights of others before your own feelings, and the feelings of others before your own rights. - John Wooden",
  "Make failure your teacher, not your undertaker.   - Zig Ziglar",
  "Note that this journey is uniquely yours, no one elses. So the path has to be your own. - Jon Kabat-Zinn",
  "People are weird. When we find someone with weirdness that is compatible with ours, we team up and call it love. - Dr. Seuss",
  "Judge a man by his questions rather than his answers. - Voltaire"
]