backup_stoics = [
  "To love only what happens, what was destined. No greater harmony. - Marcus Aurelius",
  "Hang on to your youthful enthusiasms - you'll be able to use them better when you're older. - Seneca",
  "Man conquers the world by conquering himself. - Zeno",
  "Associate with people who are likely to improve you. - Seneca",
  "How ridiculous and how strange to be surprised at anything which happens in life. - Marcus Aurelius",
  "The soul becomes dyed with the color of its thoughts. - Marcus Aurelius",
  "It is not events that disturb people, it is their judgements concerning them. - Marcus Aurelius",
  "We suffer more often in imagination than in reality. - Seneca",
  "Associate with people who are likely to improve you. - Seneca",
  "Waste no more time arguing about what a good man should be. Be one. - Marcus Aurelius",
  "The soul becomes dyed with the color of its thoughts. - Marcus Aurelius",
  "How ridiculous and how strange to be surprised at anything which happens in life. - Marcus Aurelius",
  "The goal of life is living in agreement with Nature. - Zeno",
  "How ridiculous and how strange to be surprised at anything which happens in life. - Marcus Aurelius",
  "It is not the man who has too little, but the man who craves more, that is poor. - Seneca",
  "Be tolerant with others and strict with yourself. - Marcus Aurelius",
  "Circumstances don't make the man, they only reveal him to himself. - Epictetus",
  "It is not the man who has too little, but the man who craves more, that is poor. - Seneca",
  "Sometimes even to live is an act of courage. - Seneca",
  "Receive without pride, let go without attachment. - Marcus Aurelius",
  "Better to trip with the feet than with the tongue. - Zeno",
  "It is not the man who has too little, but the man who craves more, that is poor. - Seneca",
  "We suffer more often in imagination than in reality. - Seneca",
  "Waste no more time arguing about what a good man should be. Be one. - Marcus Aurelius",
  "He who follows reason in all things is both tranquil and active at the same time, and also cheerful and collected. - Marcus Aurelius",
  "You're subject to sorrow, fear, jealousy, anger and inconsistency. That's the real reason you should admit that you are not wise. - Marcus Aurelius",
  "We have two ears and one mouth, so we should listen more than we say. - Zeno",
  "If it's not right, don't do it. If it's not true, don't say it. - Marcus Aurelius",
  "Circumstances don't make the man, they only reveal him to himself. - Epictetus",
  "Who is your master? Anyone who has control over things upon which you've set your heart, or over things which you seek to avoid. - Epictetus",
  "The goal of life is living in agreement with Nature. - Zeno",
  "Be tolerant with others and strict with yourself. - Marcus Aurelius",
  "The more we value things outside our control, the less control we have. - Marcus Aurelius",
  "We have two ears and one mouth, therefore we should listen twice as much as we speak. - Zeno",
  "We have two ears and one mouth, so we should listen more than we say. - Zeno",
  "Today I escaped anxiety. Or no, I discarded it, because it was within me, in my own perceptions - not outside. - Marcus Aurelius",
  "You're subject to sorrow, fear, jealousy, anger and inconsistency. That's the real reason you should admit that you are not wise. - Marcus Aurelius",
  "We have two ears and one mouth, therefore we should listen twice as much as we speak. - Zeno",
  "How ridiculous and how strange to be surprised at anything which happens in life. - Marcus Aurelius",
  "He suffers more than necessary, who suffers before it is necessary. - Seneca",
  "You are not your body and hair-style, but your capacity for choosing well. If your choices are beautiful, so too will you be. - Epictetus",
  "How ridiculous and how strange to be surprised at anything which happens in life. - Marcus Aurelius",
  "Today I escaped anxiety. Or no, I discarded it, because it was within me, in my own perceptions - not outside. - Marcus Aurelius",
  "It is not events that disturb people, it is their judgements concerning them. - Marcus Aurelius",
  "The goal of life is living in agreement with Nature. - Zeno",
  "You're subject to sorrow, fear, jealousy, anger and inconsistency. That's the real reason you should admit that you are not wise. - Marcus Aurelius",
  "You act like mortals in all that you fear, and like immortals in all that you desire. - Seneca",
  "Wealth is the slave of the wise. The master of the fool. - Seneca",
  "Better to trip with the feet than with the tongue. - Zeno",
  "You are not your body and hair-style, but your capacity for choosing well. If your choices are beautiful, so too will you be. - Epictetus",
  "Be content to seem what you really are. - Marcus Aurelius",
  "It is impossible for a man to learn what he thinks he already knows. - Epictetus",
  "Well-being is attained little by little, and nevertheless is no little thing itself. - Zeno",
  "Associate with people who are likely to improve you. - Seneca",
  "They lose the day in expectation of the night, and the night in fear of the dawn. - Seneca",
  "Man conquers the world by conquering himself. - Zeno",
  "The soul becomes dyed with the color of its thoughts. - Marcus Aurelius",
  "Reject your sense of injury and the injury itself disappears. - Marcus Aurelius",
  "It is the power of the mind to be unconquerable. - Seneca",
  "We have two ears and one mouth, so we should listen more than we say. - Zeno",
  "Receive without conceit, release without struggle. - Marcus Aurelius",
  "Better to trip with the feet than with the tongue. - Zeno",
  "Time heals what reason cannot. - Seneca",
  "If it's not right, don't do it. If it's not true, don't say it. - Marcus Aurelius",
  "Better to trip with the feet than with the tongue. - Zeno",
  "It is the power of the mind to be unconquerable. - Seneca",
  "To make the best of what is in our power, and take the rest as it occurs. - Epictetus",
  "If it's not right, don't do it. If it's not true, don't say it. - Marcus Aurelius",
  "You are not your body and hair-style, but your capacity for choosing well. If your choices are beautiful, so too will you be. - Epictetus",
  "You have power over your mind - not outside events. Realize this, and you will find strength. - Marcus Aurelius",
  "Man conquers the world by conquering himself. - Zeno",
  "He suffers more than necessary, who suffers before it is necessary. - Seneca",
  "They lose the day in expectation of the night, and the night in fear of the dawn. - Seneca",
  "Sometimes even to live is an act of courage. - Seneca",
  "The best answer to anger is silence. - Marcus Aurelius",
  "The best answer to anger is silence. - Marcus Aurelius",
  "You're subject to sorrow, fear, jealousy, anger and inconsistency. That's the real reason you should admit that you are not wise. - Marcus Aurelius",
  "To love only what happens, what was destined. No greater harmony. - Marcus Aurelius",
  "It is impossible for a man to learn what he thinks he already knows. - Epictetus",
  "Life is never incomplete if it is an honorable one. At whatever point you leave life, if you leave it in the right way, it is whole. - Seneca",
  "He who follows reason in all things is both tranquil and active at the same time, and also cheerful and collected. - Marcus Aurelius",
  "Time heals what reason cannot. - Seneca",
  "It is the power of the mind to be unconquerable. - Seneca",
  "The best answer to anger is silence. - Marcus Aurelius",
  "You are not your body and hair-style, but your capacity for choosing well. If your choices are beautiful, so too will you be. - Epictetus",
  "It is not the man who has too little, but the man who craves more, that is poor. - Seneca",
  "Well-being is attained little by little, and nevertheless is no little thing itself. - Zeno",
  "Reject your sense of injury and the injury itself disappears. - Marcus Aurelius",
  "Reject your sense of injury and the injury itself disappears. - Marcus Aurelius",
  "How ridiculous and how strange to be surprised at anything which happens in life. - Marcus Aurelius",
  "No man is free who is not master of himself. - Epictetus",
  "Receive without conceit, release without struggle. - Marcus Aurelius",
  "Circumstances don't make the man, they only reveal him to himself. - Epictetus",
  "How ridiculous and how strange to be surprised at anything which happens in life. - Marcus Aurelius",
  "Man is affected not by events but by the view he takes of them. - Seneca",
  "Man conquers the world by conquering himself. - Zeno",
  "You have power over your mind - not outside events. Realize this, and you will find strength. - Marcus Aurelius",
  "Throw me to the wolves and I will return leading the pack. - Seneca",
  "To love only what happens, what was destined. No greater harmony. - Marcus Aurelius",
  "Begin at once to live, and count each separate day as a separate life. - Seneca"
]